<?php
$output .= "<div id=\"talentlms-dialog-form\" title=\"" . __('Login') . "\">";
$output .= "	<form id=\"talentlms-dialog-login-form\" name=\"talentlms-dialog-login-form\" method=\"post\" action=\"" . htmlentities($_SERVER['REQUEST_URI']) . "\">";
$output .= "		<input type=\"hidden\" name=\"action\" value=\"dialog-post\">";
$output .= "		<fieldset>";
$output .= "			<div class=\"talentlms-form-group\">";
$output .= "				<label class=\"talentlms-form-label\" for=\"talentlms-dialog-login\">" . __('Username:') . "</label>";
$output .= "				<div class=\"talentlms-form-control\">";
$output .= "					<input type=\"text\" name=\"talentlms-dialog-login\" id=\"talentlms-dialog-login\" value=\"" . $_POST['talentlms-dialog-login'] . "\" />";
$output .= "				</div>";
$output .= "			</div>";
$output .= "			<div class=\"talentlms-form-group\">";
$output .= "				<label class=\"talentlms-form-label\" for=\"talentlms-dialog-password\">" . __('Password:') . "</label>";
$output .= "				<div class=\"talentlms-form-control\">";
$output .= "					<input type=\"password\" name=\"talentlms-dialog-password\" id=\"talentlms-dialog-password\" value=\"" . $_POST['talentlms-dialog-password'] . "\" />";
$output .= "				</div>";
$output .= "			</div>";
$output .= "		</fieldset>";
$output .= "	</form>";
$output .= "</div>";

$output .= "<script type=\"text/javascript\">";
$output .= "	jQuery(document).ready(function() {";
$output .= "		jQuery(\"#talentlms-dialog-form\").dialog({";
$output .= "			width : 350,";
$output .= "			modal : true,";
$output .= "			autoOpen : false,";
$output .= "			buttons : {";
$output .= "				\"Login\" : function() {";
$output .= "					jQuery('#talentlms-dialog-login-form').submit();";
$output .= "				},";
$output .= "				Cancel : function() {";
$output .= "					jQuery(this).dialog(\"close\");";
$output .= "				}";
$output .= "			},";
$output .= "		});";
$output .= "	});";
$output .= "	jQuery(\"#talentlms-login-dialog-opener\").click(function() {";
$output .= "		jQuery(\"#talentlms-dialog-form\").dialog(\"open\");";
$output .= "		return false;";
$output .= "	});";
$output .= "</script>";