<?php
$output .= "<div id='tl-dialog-form' title='" . __('Login') . "'>";
$output .= "	<form id='tl-dialog-login-form' name='tl-dialog-login-form' method='post' action='" . current_page_url() . "'>";
$output .= "		<input type='hidden' name='action' value='tl-dialog-post'>";
$output .= "		<fieldset>";
$output .= "			<div class='tl-form-group'>";
$output .= "				<label class='tl-form-label' for='tl-dialog-login'>" . __('Username:') . "</label>";
$output .= "				<div class='tl-form-control'>";
$output .= "					<input type='text' name='tl-dialog-login' id='tl-dialog-login' value='" . $_POST['tl-dialog-login'] . "' />";
$output .= "				</div>";
$output .= "			</div>";
$output .= "			<div class='tl-form-group'>";
$output .= "				<label class='tl-form-label' for='tl-dialog-password'>" . __('Password:') . "</label>";
$output .= "				<div class='tl-form-control'>";
$output .= "					<input type='password' name='tl-dialog-password' id='tl-dialog-password' value='" . $_POST['tl-dialog-password'] . "' />";
$output .= "				</div>";
$output .= "			</div>";
$output .= "		</fieldset>";
$output .= "	</form>";
$output .= "</div>";

$output .= "<script type='text/javascript'>";
$output .= "	jQuery(document).ready(function() {";
$output .= "		jQuery('#tl-dialog-form').dialog({";
$output .= "			width : 350,";
$output .= "			modal : true,";
$output .= "			autoOpen : false,";
$output .= "			buttons : {";
$output .= "				'Login' : function() {";
$output .= "					jQuery('#tl-dialog-login-form').submit();";
$output .= "				},";
$output .= "				Cancel : function() {";
$output .= "					jQuery(this).dialog('close');";
$output .= "				}";
$output .= "			},";
$output .= "		});";
$output .= "	});";
$output .= "	jQuery('#tl-login-dialog-opener').click(function() {";
$output .= "		jQuery('#tl-dialog-form').dialog('open');";
$output .= "		return false;";
$output .= "	});";
$output .= "</script>";